# Generated by Django 5.0.6 on 2024-06-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_state'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_method',
            field=models.CharField(default='home_delivery', max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='address.address'),
        ),
    ]
