# Generated by Django 5.0.6 on 2024-06-09 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.SmallIntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'CONFIRMED'), (3, 'CANCELLED'), (4, 'DELIVERED')], default=1)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.SmallIntegerField(choices=[(1, 'UNPAID'), (2, 'PAID'), (3, 'REFUNDED'), (4, 'PARTIALLY_REFUNDED'), (5, 'PAYMENT_FAILED'), (6, 'CANCELLED')], default=1)),
                ('delivery_method', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
    ]
