# Generated by Django 5.0.6 on 2024-06-08 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_address_uuid'),
        ('product', '0001_initial'),
        ('users', '0009_alter_customer_user_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.SmallIntegerField(choices=[('PENDING', 1), ('CONFIRMED', 2), ('CANCELLED', 3), ('DELIVERED', 4)], default=1)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.SmallIntegerField(choices=[('UNPAID', 1), ('PAID', 2), ('REFUNDED', 3), ('PARTIALLY_REFUNDED', 4), ('PAYMENT_FAILED', 5), ('CANCELLED', 6)], default=1)),
                ('shipping_address', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.SmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
