# Generated by Django 5.0.6 on 2024-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1),
        ),
    ]
