# Generated by Django 5.0.6 on 2024-06-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_shipping_address_alter_order_address'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(choices=[(1, 'Mozharul Haq')], on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer'),
        ),
    ]
