# Generated by Django 5.0.6 on 2024-06-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_method_alter_order_address_and_more'),
        ('users', '0009_alter_customer_user_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.customer'),
        ),
    ]
