# Generated by Django 5.0.6 on 2024-06-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', related_query_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
