# Generated by Django 5.0.6 on 2024-06-02 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_email_remove_customer_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, choices=[(2, 'Mozharul Haq')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', related_query_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
