# Generated by Django 5.0.6 on 2024-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('related_primary_key', models.CharField(max_length=100, null=True)),
                ('related_app', models.CharField(max_length=100, null=True)),
                ('related_model', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image_module',
            },
        ),
    ]
