# Generated by Django 5.0.6 on 2024-06-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='related_primary_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_module.imagemodel'),
        ),
    ]
