# Generated by Django 5.0.6 on 2024-06-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image_module', '0002_alter_imagemodel_related_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='related_primary_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
