# Generated by Django 5.0.6 on 2024-06-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image_module', '0003_imagemodel_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='related_app',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='related_primary_key',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='content_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
