# Generated by Django 5.0.6 on 2024-06-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_module', '0004_remove_imagemodel_related_app_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='content_Type',
            new_name='content_type',
        ),
    ]
