# Generated by Django 5.0.6 on 2024-06-13 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image_module', '0005_rename_content_type_imagemodel_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['content_type', 'object_id'], name='image_modul_content_c29c71_idx'),
        ),
    ]
