# Generated by Django 5.0.6 on 2024-06-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_module', '0006_alter_imagemodel_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='path',
        ),
    ]
