name: Secure Service Account Key Usage (With New Branch)

on:
  push:
    branches: [ main ]  # Adjust branch as needed

jobs:
  create_file_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create temporary directory
        run: mkdir -p /tmp/secrets

      - name: Construct service account key JSON (avoid exposing private key)
        env:
          SERVICE_ACCOUNT_KEY_VALUE: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          cat <<EOF > service_account.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "private_key_id": "59832af901e9f6419c2e3f81f6906611f62b956c",  # Placeholder
            "client_email": "${{ secrets.CLIENT_EMAIL }}", 
          }
          EOF
      - name: Add file to Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add service_account.json
          git commit -m "Add service account key JSON (excluding private key)"